name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Start backend
        run: npm run start --prefix backend &
      - name: Wait for backend
        run: npx wait-on http://localhost:3000/api/health
      - name: Smoke test health
        run: curl -fsS http://localhost:3000/api/health
